# Generated by Django 2.1 on 2018-08-17 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='Game Code')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dumps.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('localName', models.CharField(max_length=64)),
                ('ietfTag', models.CharField(max_length=16, verbose_name='IETF Language Tag')),
                ('isDisplayLanguage', models.BooleanField()),
                ('isLatinScript', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('manufacturer', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='gametitle',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dumps.Language', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='game',
            name='langs',
            field=models.ManyToManyField(limit_choices_to={'isDisplayLanguage': True}, to='dumps.Language', verbose_name='Text Languages'),
        ),
        migrations.AddField(
            model_name='game',
            name='system',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, to='dumps.System'),
        ),
    ]
