# Generated by Django 2.1 on 2018-08-16 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dumps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GameTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dumps.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ietfTag', models.CharField(max_length=16)),
                ('isDisplayLanguage', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='gametitle',
            name='langs',
            field=models.ManyToManyField(to='dumps.Language'),
        ),
        migrations.AddField(
            model_name='game',
            name='langs',
            field=models.ManyToManyField(limit_choices_to={'isDisplayLanguage': True}, to='dumps.Language'),
        ),
        migrations.AddField(
            model_name='game',
            name='system',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, to='dumps.System'),
        ),
    ]
