# Generated by Django 2.1 on 2018-08-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dumps', '0003_auto_20180816_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='langs',
            field=models.ManyToManyField(limit_choices_to={'isDisplayLanguage': True}, to='dumps.Language', verbose_name='Text Languages'),
        ),
        migrations.AlterField(
            model_name='gametitle',
            name='code',
            field=models.CharField(blank=True, max_length=32, verbose_name='Game Code'),
        ),
        migrations.AlterField(
            model_name='gametitle',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dumps.Language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='ietfTag',
            field=models.CharField(max_length=16, verbose_name='IETF Language Tag'),
        ),
    ]
