# Generated by Django 2.1 on 2018-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumps', '0004_auto_20180816_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='isLatinScript',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
