# Generated by Django 2.1 on 2018-08-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumps', '0005_language_islatinscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='localName',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
