# Generated by Django 2.0.1 on 2018-01-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbs.System')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=16)),
                ('pcb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pcbs.PCB')),
            ],
        ),
    ]
