# Generated by Django 2.0.1 on 2018-01-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0003_auto_20180129_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revision',
            new_name='PCBRevision',
        ),
        migrations.AlterModelOptions(
            name='pcbrevision',
            options={'verbose_name': 'PCB Revision', 'verbose_name_plural': 'PCB Revisions'},
        ),
    ]
