# Generated by Django 2.0.1 on 2018-01-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0005_auto_20180129_1900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pcbrevision',
            unique_together={('pcb', 'label')},
        ),
    ]
