# Generated by Django 2.0.1 on 2018-01-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0007_pcbrevision_is_base_revision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcbrevision',
            old_name='differences',
            new_name='changes',
        ),
    ]
