# Generated by Django 2.0.1 on 2018-02-03 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0008_auto_20180129_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCBGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=16)),
                ('is_default_group', models.BooleanField(default=False, verbose_name='Default Group')),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbs.System')),
            ],
            options={
                'verbose_name_plural': 'PCB Groups',
                'verbose_name': 'PCB Group',
            },
        ),
        migrations.RemoveField(
            model_name='pcb',
            name='system',
        ),
        migrations.AddField(
            model_name='pcb',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbs.PCBGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='pcbgroup',
            unique_together={('system', 'label')},
        ),
    ]
