# Generated by Django 2.0.1 on 2018-02-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0009_auto_20180203_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcbgroup',
            old_name='label',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='pcbgroup',
            unique_together={('system', 'name')},
        ),
    ]
