# Generated by Django 2.2.1 on 2019-05-02 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0010_auto_20180203_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Manufacturers',
                'verbose_name': 'Manufacturer',
            },
        ),
        migrations.AddField(
            model_name='system',
            name='manufacturer_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbs.Manufacturer'),
        ),
    ]
