# Generated by Django 2.2.1 on 2019-05-02 16:08

from django.db import migrations


def create_Manufacturers(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Manufacturer = apps.get_model("pcbs", "Manufacturer")
    System = apps.get_model("pcbs", "System")
    for system in System.objects.all():
        manufacturer, created = Manufacturer.objects.get_or_create(name=system.manufacturer)
        system.manufacturer_fk = manufacturer
        system.manufacturer = ''
        system.save()


def remove_Manufacturers(apps, schema_editor):
    System = apps.get_model("pcbs", "System")
    for system in System.objects.all():
        if (system.manufacturer_fk is not None):
            system.manufacturer = system.manufacturer_fk.name
        system.manufacturer_fk = None
        system.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0011_auto_20190502_1608'),
    ]

    operations = [
        migrations.RunPython(create_Manufacturers, remove_Manufacturers),
    ]
