# Generated by Django 2.2.1 on 2019-05-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0012_auto_20190502_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='manufacturer',
        ),
    ]
