# Generated by Django 2.2.1 on 2019-05-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0013_remove_system_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='manufacturer_fk',
            new_name='manufacturer',
        ),
    ]
