# Generated by Django 2.2.1 on 2019-05-02 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0016_auto_20190502_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcb',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbs.Manufacturer'),
        ),
        migrations.AddField(
            model_name='pcb',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbs.System'),
        ),
    ]
