# Generated by Django 2.2.1 on 2019-05-02 16:43

from django.db import migrations


def copy_PCBGroupDetails2PCB(apps, schema_editor):
    PCB = apps.get_model("pcbs", "PCB")
    for pcb in PCB.objects.all():
        pcb.manufacturer = pcb.group.manufacturer_fk
        pcb.system = pcb.group.system
        pcb.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0017_auto_20190502_1643'),
    ]

    operations = [
        migrations.RunPython(copy_PCBGroupDetails2PCB),
    ]
