# Generated by Django 2.2.1 on 2019-05-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0019_auto_20190502_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='slug',
            field=models.SlugField(max_length=64, null=True, unique=True),
        ),
    ]
