# Generated by Django 2.2.1 on 2019-05-11 16:42

from django.db import migrations


def copy_name_to_slug(apps, schema_editor):
    Systems = apps.get_model("pcbs", "System")
    for system in Systems.objects.all():
        name = system.name
        system.slug = name.replace(' ', '-')
        system.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0020_system_slug'),
    ]

    operations = [
        migrations.RunPython(copy_name_to_slug),
    ]
